# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  #vmImage: 'Ubuntu 16.04'
  name: 'smarthotelprod'

variables:
  imageName: 'smarthotels/reviews:$(Build.BuildId)'
  
steps:
#- script: docker build -f Dockerfile -t $(imageName) .
#  displayName: 'docker build'
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: shregistry.azurecr.io
    dockerFile: Source/Backend/src/SmartHotel.Services.Reviews/Dockerfile
    useDefaultContext: false
    buildContext: Source/Backend/src/SmartHotel.Services.Reviews
    imageName: '$(imageName)'
    includeLatestTag: true
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: shregistry.azurecr.io
    command: 'Push an image'
    imageName: '$(imageName)'
    includeLatestTag: true
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: shregistry.azurecr.io
    command: 'Push an image'
    imageName: 'smarthotels/reviews:latest'
    includeLatestTag: true
